In [21]:
import numpy as np

matrix1=np.array([[1,3,4],[5,7,8],[2,6,9]])
print("matrix:\n",matrix1)


matrix:
 [[1 3 4]
 [5 7 8]
 [2 6 9]]


In [22]:
from scipy import stats
mean=np.mean(matrix1)
median=np.median(matrix1)
mode=stats.mode(matrix1,axis=None)

print("Mean::",mean)
print("Median::",median)
print("Mode::",mode)

Mean:: 5.0
Median:: 5.0
Mode:: ModeResult(mode=1, count=1)


In [23]:
transpose=np.transpose(matrix1)
print("Transpose::",transpose)

Transpose:: [[1 5 2]
 [3 7 6]
 [4 8 9]]


In [26]:
determinant=np.linalg.det(matrix1)
print("Determinant::",determinant)

Determinant:: -7.999999999999991


In [24]:
inverse=np.linalg.inv(matrix1)
print("Inverse::",inverse)

Inverse:: [[-1.87500000e+00  3.75000000e-01  5.00000000e-01]
 [ 3.62500000e+00 -1.25000000e-01 -1.50000000e+00]
 [-2.00000000e+00  5.55111512e-17  1.00000000e+00]]


In [28]:
if determinant==0:
    print("matrix is singular there is no inverse:")
else:
    inverse=np.linalg.inv(matrix1)
    print("Matrix::",matrix1)
    print("Inverse::",inverse)

Matrix:: [[1 3 4]
 [5 7 8]
 [2 6 9]]
Inverse:: [[-1.87500000e+00  3.75000000e-01  5.00000000e-01]
 [ 3.62500000e+00 -1.25000000e-01 -1.50000000e+00]
 [-2.00000000e+00  5.55111512e-17  1.00000000e+00]]


In [33]:
m1=np.array([[1,2],[4,5]])
m2=np.array([[7,8],[6,9]])
print("Matrix1::\n",m1)
print("Matrix2::\n",m2)
mul=np.dot(m1,m2)
print("product::\n",mul)

Matrix1::
 [[1 2]
 [4 5]]
Matrix2::
 [[7 8]
 [6 9]]
product::
 [[19 26]
 [58 77]]
